/**
 * ResolveAI API service
 * ----------------------
 * Single place where the frontend talks to FastAPI.
 */

const API_BASE_URL =
  import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000'

const ANALYZE_ENDPOINT_PATH = '/analyze'


// ==================================================
// API ERROR
// ==================================================

export class ApiError extends Error {
  constructor(message, type = 'api_error', status = null) {
    super(message)

    this.name = 'ApiError'

    this.type = type

    this.status = status
  }
}


// ==================================================
// ERROR RESPONSE PARSER
// ==================================================

async function parseErrorBody(response) {

  try {

    const data = await response.json()

    return (
      data.detail ||
      data.message ||
      JSON.stringify(data)
    )

  } catch {

    return (
      response.statusText ||
      'Unknown error'
    )

  }
}


// ==================================================
// BACKEND HEALTH CHECK
// ==================================================

export async function checkBackendHealth() {

  try {

    const response = await fetch(
      `${API_BASE_URL}/health`,
      {
        method: 'GET',

        signal:
          AbortSignal.timeout(5000),
      }
    )

    return response.ok

  } catch {

    return false

  }
}


// ==================================================
// ANALYZE INCIDENT
// ==================================================

/**
 * POST /analyze
 *
 * Sends:
 *
 * {
 *   title,
 *   description
 * }
 *
 * Backend returns:
 *
 * - Ticket ID
 * - Category
 * - Priority
 * - Root Cause
 * - Resolution
 * - Status
 *
 * AND:
 *
 * - Agent status
 * - Agent steps
 * - Tools used
 * - Execution trace
 */

export async function analyzeIncident(
  incident
) {

  let response

  try {

    response = await fetch(
      `${API_BASE_URL}${ANALYZE_ENDPOINT_PATH}`,
      {
        method: 'POST',

        headers: {
          'Content-Type':
            'application/json',
        },

        body: JSON.stringify({

          title:
            incident.title,

          description:
            incident.description,

        }),

        signal:
          AbortSignal.timeout(60000),
      }
    )

  } catch (err) {

    if (
      err.name === 'TimeoutError' ||
      err.name === 'AbortError'
    ) {

      throw new ApiError(

        'The backend did not respond in time. The AI agent may still be processing the incident.',

        'network'

      )

    }

    throw new ApiError(

      `Could not reach the ResolveAI backend at ${API_BASE_URL}. Is it running?`,

      'backend_unavailable'

    )

  }


  // ==================================================
  // ENDPOINT NOT FOUND
  // ==================================================

  if (response.status === 404) {

    throw new ApiError(

      `The backend at ${API_BASE_URL} does not expose ${ANALYZE_ENDPOINT_PATH}.`,

      'not_implemented',

      404

    )

  }


  // ==================================================
  // OTHER API ERRORS
  // ==================================================

  if (!response.ok) {

    const message =
      await parseErrorBody(response)

    throw new ApiError(

      message,

      'api_error',

      response.status

    )

  }


  // ==================================================
  // SUCCESSFUL RESPONSE
  // ==================================================

  const data =
    await response.json()


  // ==================================================
  // NORMALIZE AGENT TRACE
  // ==================================================

  /*
   * The backend returns the actual execution trace
   * generated by run_agent().
   *
   * Example:
   *
   * [
   *   {
   *     step: 1,
   *     type: "planner",
   *     action: "knowledge_search",
   *     status: "decided"
   *   },
   *
   *   {
   *     step: 1,
   *     type: "tool",
   *     action: "knowledge_search",
   *     status: "completed"
   *   }
   * ]
   *
   * If an older backend is running and does not yet
   * return execution_trace, use an empty array rather
   * than breaking the frontend.
   */

  return {

    ...data,

    execution_trace:
      Array.isArray(
        data.execution_trace
      )
        ? data.execution_trace
        : [],

    tools_used:
      Array.isArray(
        data.tools_used
      )
        ? data.tools_used
        : [],

    agent_steps:
      data.agent_steps ?? 0,

    agent_status:
      data.agent_status ||
      'completed',

  }

}


// ==================================================
// CONFIRM ISSUE RESOLVED
// ==================================================

/**
 * POST /tickets/{ticket_id}/resolve
 *
 * Called when the user confirms:
 *
 * "Yes, Issue Resolved"
 *
 * Backend changes the ticket to CLOSED.
 */

export async function resolveTicket(
  ticketId
) {

  if (!ticketId) {

    throw new ApiError(

      'Ticket ID is missing.',

      'validation'

    )

  }


  let response

  try {

    response = await fetch(

      `${API_BASE_URL}/tickets/${encodeURIComponent(ticketId)}/resolve`,

      {
        method: 'POST',

        headers: {
          'Content-Type':
            'application/json',
        },

        signal:
          AbortSignal.timeout(10000),

      }

    )

  } catch (err) {

    if (
      err.name === 'TimeoutError' ||
      err.name === 'AbortError'
    ) {

      throw new ApiError(

        'The backend did not respond while closing the ticket.',

        'network'

      )

    }

    throw new ApiError(

      'Could not reach the ResolveAI backend.',

      'backend_unavailable'

    )

  }


  if (!response.ok) {

    const message =
      await parseErrorBody(response)

    throw new ApiError(

      message,

      'api_error',

      response.status

    )

  }


  return response.json()

}


// ==================================================
// ISSUE NOT RESOLVED
// ==================================================

/**
 * POST /tickets/{ticket_id}/keep-open
 *
 * Called when the user says:
 *
 * "No, Still Having Issue"
 *
 * The ticket remains OPEN.
 */

export async function keepTicketOpen(
  ticketId
) {

  if (!ticketId) {

    throw new ApiError(

      'Ticket ID is missing.',

      'validation'

    )

  }


  let response

  try {

    response = await fetch(

      `${API_BASE_URL}/tickets/${encodeURIComponent(ticketId)}/keep-open`,

      {
        method: 'POST',

        headers: {
          'Content-Type':
            'application/json',
        },

        signal:
          AbortSignal.timeout(10000),

      }

    )

  } catch (err) {

    if (
      err.name === 'TimeoutError' ||
      err.name === 'AbortError'
    ) {

      throw new ApiError(

        'The backend did not respond while updating the ticket.',

        'network'

      )

    }

    throw new ApiError(

      'Could not reach the ResolveAI backend.',

      'backend_unavailable'

    )

  }


  if (!response.ok) {

    const message =
      await parseErrorBody(response)

    throw new ApiError(

      message,

      'api_error',

      response.status

    )

  }


  return response.json()

}


// ==================================================
// GET CURRENT TICKET
// ==================================================

export async function getTicket(
  ticketId
) {

  if (!ticketId) {

    throw new ApiError(

      'Ticket ID is missing.',

      'validation'

    )

  }


  let response

  try {

    response = await fetch(

      `${API_BASE_URL}/tickets/${encodeURIComponent(ticketId)}`,

      {
        method: 'GET',

        signal:
          AbortSignal.timeout(10000),

      }

    )

  } catch {

    throw new ApiError(

      'Could not reach the ResolveAI backend.',

      'backend_unavailable'

    )

  }


  if (!response.ok) {

    const message =
      await parseErrorBody(response)

    throw new ApiError(

      message,

      'api_error',

      response.status

    )

  }


  return response.json()

}